### ISSUE TITLE
Order by category

### ISSUE THREAD

**Issue by Matix-Media** [AlphaSoundZ/apollo#16]
Add an option to order by category.

For example:  
`GET /api/v5/user?query=max%20mustermann&order_by=amount_of_devices&order_strategy=DESC`

```jsonc
{
    "order": {
        "by": "amount_of_devices",
        "strategy": "DESC"
    },
    "page": {...}
    "users": [...] // Or data or something idk
}
```

**Comment by AlphaSoundZ** [comment]
Order by index does not work!

Use instead:
Example:
```
order_by=class.id&order_strategy=DESC
```
